apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiGW
  template:
    metadata:
      labels:
        app: apiGW
    spec:
      containers:
        - name: api-gw
          image: env.IMAGE_NAME_API
          ports:
            - containerPort: 3000
