apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gw
  template:
    metadata:
      labels:
        app: api-gw
    spec:
      containers:
        - name: api-gw
          image: gcr.io/repaso-examen-500009/api-gw
          ports:
            - containerPort: 3000