apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-storage
spec:
  serviceName: backend-storage
  replicas: 1
  selector:
    matchLabels:
      app: backend-storage
  template:
    metadata:
      labels:
        app: backend-storage
    spec:
      containers:
        - name: storage
          image: gcr.io/repaso-examen-500009/backend-storage
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: 
          -ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi