apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-router
spec:
  serviceName: svc-router
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
        - name: router
          image: env.IMAGE_NAME_ROUTER
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: <placeholder>
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: <placeholder>
      spec:
        accessModes: <placeholder>
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
